spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

app:
  storage-path: ${APP_STORAGE_PATH}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

knife4j:
  enable: false